Repository 100mslive/100ms-flutter, pull requests merged in 2022-12, with the labels that each got.

#937 Hls iOS pip
  example/ios/Podfile
  example/ios/Podfile.lock
  example/ios/Runner.xcodeproj/project.pbxproj
  example/ios/Runner/Info.plist
  example/lib/data_store/meeting_store.dart
  example/lib/hls-streaming/bottom_sheets/hls_viewer_settings.dart
  example/lib/hls_viewer/hls_viewer.dart
  example/pubspec.lock
  example/pubspec.yaml
  ios/Classes/Models/HMSTrackSettingsExtension.swift
Labels: enhancement

#1005 Added permission fix for settings UI
  example/lib/common/util/utility_components.dart
  example/lib/data_store/meeting_store.dart
  example/lib/hls-streaming/bottom_sheets/hls_more_settings.dart
  example/lib/hms_sdk_interactor.dart
  ios/Classes/SwiftHmssdkFlutterPlugin.swift
Labels: bug

#1004 RTC stats ui updated
  example/lib/common/ui/organisms/rtc_stats_view.dart
  example/lib/data_store/meeting_store.dart
  example/lib/model/peer_track_node.dart
Labels: enhancement

#1008 viewer tile fix
  example/lib/data_store/meeting_store.dart
  example/lib/hls-streaming/bottom_sheets/hls_participant_sheet.dart
  example/lib/hls-streaming/hls_broadcaster_page.dart
Labels: bug

#1010 using JSON for package versioning
  android/build.gradle
  example/android/Gemfile.lock
  example/ios/Gemfile.lock
  example/ios/Podfile.lock
  example/pubspec.lock
  ios/hmssdk_flutter.podspec
  lib/src/common/constant.dart
  sdk-versions.json
Labels: enhancement, P1

#1012 HMSQualityLimitationReasons
  android/src/main/kotlin/live/hms/hmssdk_flutter/HMSRtcStatsExtension.kt
  lib/hmssdk_flutter.dart
  lib/src/enum/hms_Quality_limitation_reason.dart
  lib/src/model/hms_local_video_stats.dart
  lib/src/model/hms_quality_limitation_reasons.dart
Labels: enhancement, P0

#1014 Pin Tile Mode
  example/lib/common/ui/organisms/audio_tile.dart
  example/lib/common/ui/organisms/grid_audio_view.dart
  example/lib/common/ui/organisms/remote_peer_tile_dialog.dart
  example/lib/common/ui/organisms/video_tile.dart
  example/lib/data_store/meeting_store.dart
  example/lib/hls-streaming/meeting_mode/hls_grid_view.dart
  example/lib/model/peer_track_node.dart
Labels: enhancement, P1

#1016 Fix/black tile iOS
  example/lib/common/ui/organisms/full_screen_view.dart
  example/lib/common/ui/organisms/grid_video_view.dart
  example/lib/data_store/meeting_store.dart
  example/lib/hls-streaming/meeting_mode/hls_grid_view.dart
Labels: bug, P1

#1020 HMSSubscribeDegradationParams added
  android/src/main/kotlin/live/hms/hmssdk_flutter/HMSSubscribeDegradationParams.kt
  android/src/main/kotlin/live/hms/hmssdk_flutter/hms_role_components/SubscribeSettings.kt
  ios/Classes/Models/HMSSubscribeSettingsExtension.swift
  lib/hmssdk_flutter.dart
  lib/src/model/hms_remote_video_track.dart
  lib/src/model/hms_role.dart
  lib/src/model/hms_subscribe_degradation_params.dart
  lib/src/model/hms_subscribe_settings.dart
Labels: enhancement, P0

#1024 Added json parsing logic in sdk
  android/build.gradle
  example/lib/hms_app_settings.dart
  example/pubspec.yaml
  ios/hmssdk_flutter.podspec
  lib/assets/sdk-versions.json
  lib/hmssdk_flutter.dart
  lib/src/common/constant.dart
  lib/src/manager/hms_sdk_manager.dart
  pubspec.yaml
Labels: enhancement, P1

#1033 Simulcast layer check fix
  example/lib/common/ui/organisms/video_tile.dart
Labels: bug, P0
