Repository 100mslive/100ms-flutter, pull requests merged in 2023-04, with the labels that each got.

#1217 Release 1.4.0: Develop to main
  .gitignore
  CHANGELOG.md
  android/src/main/kotlin/live/hms/hmssdk_flutter/HMSResultExtension.kt
  android/src/main/kotlin/live/hms/hmssdk_flutter/HmssdkFlutterPlugin.kt
  android/src/main/kotlin/live/hms/hmssdk_flutter/methods/HMSCommonAction.kt
  example/ExampleAppChangelog.txt
  example/android/Gemfile.lock
  example/android/app/build.gradle
  example/android/app/src/main/AndroidManifest.xml
  example/ios/Gemfile.lock
  example/ios/Podfile.lock
  example/ios/Runner.xcodeproj/project.pbxproj
  example/ios/Runner/Info.plist
  example/lib/common/app_dialogs/hls_aspect_ratio_option_dialog.dart
  example/lib/common/app_dialogs/track_change_request_dialog.dart
  example/lib/common/bottom_sheets/app_settings_bottom_sheet.dart
  example/lib/common/bottom_sheets/logger_view_bottom_sheet.dart
  example/lib/common/bottom_sheets/meeting_mode_bottom_sheet.dart
  example/lib/common/bottom_sheets/more_settings_bottom_sheet.dart
  example/lib/common/bottom_sheets/viewer_settings_bottom_sheet.dart
  example/lib/common/peer_widgets/network_icon_widget.dart
  example/lib/common/util/log_writer.dart
  example/lib/common/util/utility_function.dart
  example/lib/common/widgets/degrade_tile.dart
  example/lib/common/widgets/peer_tile.dart
  example/lib/common/widgets/pip_view.dart
  example/lib/enum/meeting_mode.dart
  example/lib/hls_viewer/hls_player.dart
  example/lib/hls_viewer/hls_viewer_page.dart
  example/lib/hms_sdk_interactor.dart
  example/lib/home_screen/screen_controller.dart
  example/lib/meeting/meeting_page.dart
  example/lib/meeting/meeting_store.dart
  example/lib/preview/preview_page.dart
  example/lib/preview/preview_store.dart
  example/lib/service/constant.dart
  example/lib/service/room_service.dart
  example/pubspec.lock
  example/pubspec.yaml
  ios/Classes/Models/HMSResultExtension.swift
  ios/Classes/SwiftHmssdkFlutterPlugin.swift
  lib/assets/sdk-versions.json
  lib/hmssdk_flutter.dart
  lib/src/common/platform_methods.dart
  lib/src/hmssdk.dart
  lib/src/model/hms_custom_log.dart
  lib/src/model/hms_log.dart
  lib/src/model/hms_log_list.dart
  lib/src/model/hms_logs_listener.dart
  lib/src/service/platform_service.dart
  pubspec.yaml
Labels: chore

#1220 fix iOS compile errors on Xcode 14.3 with Flutter 3.7.10 stable version
  example/android/Gemfile.lock
  example/ios/Gemfile.lock
  example/ios/Podfile.lock
  example/lib/meeting/meeting_store.dart
  example/pubspec.lock
  example/pubspec.yaml
Labels: sample-app-UX

#1226 Update README.md
  README.md
Labels: documentation

#1240 Update package description in pubspec
  pubspec.yaml
Labels: chore

#1227 1218/auto enter pip
  android/src/main/kotlin/live/hms/hmssdk_flutter/HmssdkFlutterPlugin.kt
  android/src/main/kotlin/live/hms/hmssdk_flutter/methods/HMSPipAction.kt
  example/ExampleAppChangelog.txt
  example/android/Gemfile.lock
  example/android/app/build.gradle
  example/android/app/src/main/kotlin/live/hms/flutter/MainActivity.kt
  example/ios/Gemfile.lock
  example/ios/Runner/Info.plist
  example/lib/hls_viewer/hls_viewer_page.dart
  example/lib/meeting/meeting_store.dart
  example/pubspec.lock
  lib/src/model/hms_android_pip_controller.dart
Labels: P0, sample-app-UX

#1237 Added changes to clear logBuffer after calling getAllLogs
  android/src/main/kotlin/live/hms/hmssdk_flutter/HmssdkFlutterPlugin.kt
  example/lib/common/bottom_sheets/logger_view_bottom_sheet.dart
  ios/Classes/SwiftHmssdkFlutterPlugin.swift
Labels: enhancement, P0

#1242 1141/removed static variable
  android/src/main/kotlin/live/hms/hmssdk_flutter/HmssdkFlutterPlugin.kt
  android/src/main/kotlin/live/hms/hmssdk_flutter/views/HMSVideoView.kt
  android/src/main/kotlin/live/hms/hmssdk_flutter/views/HMSVideoViewFactory.kt
  example/android/app/src/main/kotlin/live/hms/flutter/MainActivity.kt
Labels: bug, P0

#1224 parallelly archiving Android & iOS apps to save time required
  example/android/Gemfile.lock
  example/ios/Gemfile.lock
  example/ios/Podfile
  example/ios/Podfile.lock
  example/pubspec.lock
  release-apps.sh
Labels: P0, sample-app-UX

#1247 removed unused code from SDK
  lib/src/enum/hms_network_update_listener_method.dart
  lib/src/model/hms_audio_share.dart
Labels: P1

#1251 Updated Native iOS SDK
  example/android/Gemfile.lock
  example/ios/Gemfile.lock
  example/ios/Podfile.lock
  example/pubspec.lock
  lib/assets/sdk-versions.json
Labels: chore

#1257 Updated Native Android SDK
  example/ExampleAppChangelog.txt
  example/android/Gemfile.lock
  example/ios/Gemfile.lock
  example/pubspec.lock
  lib/assets/sdk-versions.json
Labels: chore

#1261 Local Camera Capture at Max Resolution on iOS
  example/ios/Podfile.lock
  ios/Classes/Models/HMSCameraControlsAction.swift
  ios/Classes/SwiftHmssdkFlutterPlugin.swift
Labels: enhancement, P0

#1268 added check for Room instead of force unwrapping it from HMSSDK instance
  ios/Classes/Models/HMSPIPAction.swift
Labels: bug, app-UX

#1267 Release 1.5.0: Develop to main
  CHANGELOG.md
  android/src/main/kotlin/live/hms/hmssdk_flutter/Constants.kt
  android/src/main/kotlin/live/hms/hmssdk_flutter/HMSErrorLogger.kt
  android/src/main/kotlin/live/hms/hmssdk_flutter/HMSExceptionExtension.kt
  android/src/main/kotlin/live/hms/hmssdk_flutter/HmssdkFlutterPlugin.kt
  android/src/main/kotlin/live/hms/hmssdk_flutter/methods/HMSCameraControlsAction.kt
  android/src/main/kotlin/live/hms/hmssdk_flutter/methods/HMSPipAction.kt
  android/src/main/kotlin/live/hms/hmssdk_flutter/views/HMSVideoView.kt
  android/src/main/kotlin/live/hms/hmssdk_flutter/views/HMSVideoViewFactory.kt
  example/ExampleAppChangelog.txt
  example/android/Gemfile.lock
  example/android/app/build.gradle
  example/android/app/src/main/kotlin/live/hms/flutter/MainActivity.kt
  example/ios/Gemfile.lock
  example/ios/Podfile
  example/ios/Podfile.lock
  example/ios/Runner/Info.plist
  example/lib/common/app_dialogs/change_name_dialog.dart
  example/lib/common/app_dialogs/local_peer_tile_dialog.dart
  example/lib/common/bottom_sheets/logger_view_bottom_sheet.dart
  example/lib/common/peer_widgets/more_option.dart
  example/lib/common/util/app_color.dart
  example/lib/common/util/utility_components.dart
  example/lib/enum/hms_analytics_level.dart
  example/lib/enum/layout.dart
  example/lib/hls_viewer/hls_viewer_page.dart
  example/lib/meeting/meeting_store.dart
  example/lib/service/deeplink_service.dart
  example/lib/service/firebase_crashlytics_service.dart
  example/lib/service/firebase_options.dart
  example/pubspec.lock
  example/pubspec.yaml
  ios/Classes/Models/HMSCameraControlsAction.swift
  ios/Classes/Models/HMSErrorLogger.swift
  ios/Classes/Models/HMSPIPAction.swift
  ios/Classes/SwiftHmssdkFlutterPlugin.swift
  lib/assets/sdk-versions.json
  lib/hmssdk_flutter.dart
  lib/src/common/platform_methods.dart
  lib/src/enum/hms_network_update_listener_method.dart
  lib/src/model/hms_android_pip_controller.dart
  lib/src/model/hms_audio_share.dart
  lib/src/model/hms_camera_controls.dart
  lib/src/model/platform_method_response.dart
  pubspec.yaml
  release-apps.sh
Labels: chore

#1286 updated Native iOS SDK
  example/ExampleAppChangelog.txt
  example/android/Gemfile.lock
  example/ios/Gemfile.lock
  example/ios/Podfile.lock
  example/pubspec.lock
  lib/assets/sdk-versions.json
Labels: chore
