Repository 100mslive/100ms-flutter, pull requests merged in 2023-06, with the labels that each got.

#1362 Added api's for iOS Control Centre
  example/lib/common/bottom_sheets/more_settings_bottom_sheet.dart
  example/lib/hms_sdk_interactor.dart
  example/lib/meeting/meeting_store.dart
  ios/Classes/Actions/HMSAudioDeviceAction.swift
  ios/Classes/SwiftHmssdkFlutterPlugin.swift
  lib/src/common/platform_methods.dart
  lib/src/hmssdk.dart
Labels: enhancement, P0

#1355 Hls player ios
  android/src/main/kotlin/live/hms/hmssdk_flutter/hls_player/HMSPlayerStatsExtension.kt
  example/ExampleAppChangelog.txt
  example/android/app/build.gradle
  example/android/build.gradle
  example/ios/Podfile.lock
  example/ios/Runner/Info.plist
  example/lib/common/app_dialogs/hls_aspect_ratio_option_dialog.dart
  example/lib/common/bottom_sheets/viewer_settings_bottom_sheet.dart
  example/lib/hls_viewer/hls_player.dart
  example/lib/hls_viewer/hls_stats_view.dart
  example/lib/main.dart
  example/lib/meeting/meeting_page.dart
  example/lib/meeting/meeting_store.dart
  example/pubspec.lock
  example/pubspec.yaml
  ios/Classes/HLSPlayer/HMSHLSCueExtension.swift
  ios/Classes/HLSPlayer/HMSHLSPlaybackStateExtension.swift
  ios/Classes/HLSPlayer/HMSHLSPlayerAction.swift
  ios/Classes/HLSPlayer/HMSHLSPlayerStatsExtension.swift
  ios/Classes/HLSPlayer/HMSHLSStatsHandler.swift
  ios/Classes/HLSPlayer/HMSHLSStreamViewController.swift
  ios/Classes/SwiftHmssdkFlutterPlugin.swift
  ios/Classes/Views/HMSHLSPlayerView.swift
  ios/Classes/Views/HMSHLSPlayerViewFactory.swift
  ios/hmssdk_flutter.podspec
  lib/assets/sdk-versions.json
  lib/src/model/hls_player_model/hms_hls_player_stats.dart
  sample apps/flutter-quickstart-app/pubspec.yaml
Labels: enhancement, P0

#1353 1089/hls player support
  android/build.gradle
  android/src/main/kotlin/live/hms/hmssdk_flutter/Constants.kt
  android/src/main/kotlin/live/hms/hmssdk_flutter/HmssdkFlutterPlugin.kt
  android/src/main/kotlin/live/hms/hmssdk_flutter/hls_player/HLSStatsHandler.kt
  android/src/main/kotlin/live/hms/hmssdk_flutter/hls_player/HMSHLSCueExtension.kt
  android/src/main/kotlin/live/hms/hmssdk_flutter/hls_player/HMSHLSPlaybackStateExtension.kt
  android/src/main/kotlin/live/hms/hmssdk_flutter/hls_player/HMSHLSPlayerAction.kt
  android/src/main/kotlin/live/hms/hmssdk_flutter/hls_player/HMSPlayerStatsExtension.kt
  android/src/main/kotlin/live/hms/hmssdk_flutter/views/HMSHLSPlayer.kt
  android/src/main/kotlin/live/hms/hmssdk_flutter/views/HMSHLSPlayerFactory.kt
  android/src/main/kotlin/live/hms/hmssdk_flutter/views/HMSVideoView.kt
  android/src/main/kotlin/live/hms/hmssdk_flutter/views/HMSVideoViewFactory.kt
  android/src/main/res/layout/hms_hls_player.xml
  example/ExampleAppChangelog.txt
  example/android/app/build.gradle
  example/android/build.gradle
  example/ios/Podfile.lock
  example/ios/Runner/Info.plist
  example/lib/common/app_dialogs/hls_aspect_ratio_option_dialog.dart
  example/lib/common/bottom_sheets/viewer_settings_bottom_sheet.dart
  example/lib/common/util/utility_function.dart
  example/lib/hls_viewer/hls_player.dart
  example/lib/hls_viewer/hls_stats_view.dart
  example/lib/hls_viewer/hls_viewer_page.dart
  example/lib/home_screen/screen_controller.dart
  example/lib/main.dart
  example/lib/meeting/meeting_page.dart
  example/lib/meeting/meeting_store.dart
  example/lib/preview/preview_page.dart
  example/pubspec.lock
  example/pubspec.yaml
  ios/Classes/HLSPlayer/HMSHLSCueExtension.swift
  ios/Classes/HLSPlayer/HMSHLSPlaybackStateExtension.swift
  ios/Classes/HLSPlayer/HMSHLSPlayerAction.swift
  ios/Classes/HLSPlayer/HMSHLSPlayerStatsExtension.swift
  ios/Classes/HLSPlayer/HMSHLSStatsHandler.swift
  ios/Classes/HLSPlayer/HMSHLSStreamViewController.swift
  ios/Classes/SwiftHmssdkFlutterPlugin.swift
  ios/Classes/Views/HMSHLSPlayerView.swift
  ios/Classes/Views/HMSHLSPlayerViewFactory.swift
  ios/hmssdk_flutter.podspec
  lib/assets/sdk-versions.json
  lib/hmssdk_flutter.dart
  lib/src/common/platform_methods.dart
  lib/src/enum/hms_hls_playback_event_method.dart
  lib/src/enum/hms_hls_playback_state.dart
  lib/src/model/hls_player_model/hms_hls_player_stats.dart
  lib/src/model/hms_hls_cue.dart
  lib/src/model/hms_hls_playback_event_listener.dart
  lib/src/model/hms_hls_player_controller.dart
  lib/src/model/platform_method_response.dart
  lib/src/service/platform_service.dart
  lib/src/ui/meeting/hms_hls_player.dart
  sample apps/flutter-quickstart-app/pubspec.yaml
Labels: enhancement, P0

#1368 1367/hardware echo cancellation
  android/src/main/kotlin/live/hms/hmssdk_flutter/HMSTrackSettingsExtension.kt
Labels: enhancement, P0

#1380 added null safety checks
  .gitignore
  example/android/Gemfile.lock
  example/ios/Gemfile.lock
  example/ios/Podfile.lock
  example/ios/Runner.xcodeproj/project.pbxproj
  example/lib/meeting/meeting_store.dart
  example/lib/preview/preview_store.dart
  example/pubspec.lock
  ios/Classes/SwiftHmssdkFlutterPlugin.swift
  sample apps/bloc/pubspec.lock
  sample apps/flutter-audio-room-quickstart/pubspec.lock
  sample apps/flutter-hls-quickstart/pubspec.lock
  sample apps/flutter-quickstart-app/pubspec.lock
  sample apps/getx/pubspec.lock
  sample apps/hms-callkit-app/.flutter-plugins
  sample apps/hms-callkit-app/.flutter-plugins-dependencies
  sample apps/hms-callkit-app/pubspec.lock
  sample apps/mobx/pubspec.lock
  sample apps/riverpod/pubspec.lock
Labels: bug, P0

#1330 Hybrid composition videoview
  example/ExampleAppChangelog.txt
  example/lib/meeting/meeting_store.dart
  lib/src/ui/meeting/hms_video_view.dart
Labels: enhancement, P0

#1385 Update README.md
  README.md
Labels: documentation

#1379 Added methods to enable the always ON Screen capabilities
  android/src/main/kotlin/live/hms/hmssdk_flutter/HmssdkFlutterPlugin.kt
  example/lib/hms_sdk_interactor.dart
  example/lib/meeting/meeting_page.dart
  example/lib/meeting/meeting_store.dart
  example/pubspec.yaml
  ios/Classes/SwiftHmssdkFlutterPlugin.swift
  lib/src/common/platform_methods.dart
  lib/src/hmssdk.dart
Labels: enhancement, P1

#1403 Release 1.7.1: Added support to Not mute local peer when incoming phone call is ringing
  .trunk/trunk.yaml
  CHANGELOG.md
  android/src/main/AndroidManifest.xml
  android/src/main/kotlin/live/hms/hmssdk_flutter/HMSTrackSettingsExtension.kt
  example/android/app/src/main/AndroidManifest.xml
  example/ios/Podfile.lock
  example/lib/common/util/utility_function.dart
  example/pubspec.lock
  example/pubspec.yaml
  ios/Classes/SwiftHmssdkFlutterPlugin.swift
  lib/assets/sdk-versions.json
  lib/src/enum/hms_phone_call_state.dart
  lib/src/model/hls_player/hms_hls_player_controller.dart
  lib/src/model/hms_audio_track_setting.dart
  pubspec.yaml
Labels: enhancement, P0
