Repository 100mslive/100ms-flutter, pull requests merged in 2023-05, with the labels that each got.

#1291 Feature/1275 - Add support for Music Mode
  example/android/Gemfile.lock
  example/assets/icons/audio_mode.svg
  example/ios/Gemfile.lock
  example/ios/Podfile.lock
  example/lib/common/app_dialogs/audio_mode_select_dialog.dart
  example/lib/common/bottom_sheets/app_settings_bottom_sheet.dart
  example/lib/common/util/utility_function.dart
  example/lib/hms_sdk_interactor.dart
  example/lib/home_screen/user_detail_screen.dart
  example/lib/meeting/meeting_store.dart
  example/pubspec.lock
  ios/Classes/Models/HMSAudioFilePlayerNodeExtension.swift
  ios/Classes/Models/HMSTrackSettingsExtension.swift
  ios/Classes/SwiftHmssdkFlutterPlugin.swift
  lib/hmssdk_flutter.dart
  lib/src/enum/hms_audio_mode.dart
  lib/src/model/hms_audio_file_player_node.dart
  lib/src/model/hms_audio_track_setting.dart
  lib/src/model/hms_camera_controls.dart
Labels: enhancement, P1

#1276 1259/session store android
  android/build.gradle
  android/src/main/kotlin/live/hms/hmssdk_flutter/HMSKeyChangeObserver.kt
  android/src/main/kotlin/live/hms/hmssdk_flutter/HmssdkFlutterPlugin.kt
  android/src/main/kotlin/live/hms/hmssdk_flutter/methods/HMSSessionMetadataAction.kt
  android/src/main/kotlin/live/hms/hmssdk_flutter/methods/HMSSessionStoreAction.kt
  example/ExampleAppChangelog.txt
  example/android/app/build.gradle
  example/assets/icons/spotlight.svg
  example/ios/Podfile.lock
  example/ios/Runner/Info.plist
  example/lib/common/app_dialogs/local_peer_tile_dialog.dart
  example/lib/common/app_dialogs/remote_peer_tile_dialog.dart
  example/lib/common/bottom_sheets/chat_bottom_sheet.dart
  example/lib/common/peer_widgets/more_option.dart
  example/lib/common/widgets/message_container.dart
  example/lib/enum/session_store_key.dart
  example/lib/meeting/meeting_page.dart
  example/lib/meeting/meeting_store.dart
  lib/assets/sdk-versions.json
  lib/hmssdk_flutter.dart
  lib/src/common/platform_methods.dart
  lib/src/enum/hms_action_result_listener_method.dart
  lib/src/enum/hms_key_change_listener_method.dart
  lib/src/enum/hms_update_listener_method.dart
  lib/src/hmssdk.dart
  lib/src/model/hms_key_change_listener.dart
  lib/src/model/hms_key_change_observer.dart
  lib/src/model/hms_session_store.dart
  lib/src/model/hms_update_listener.dart
  lib/src/model/platform_method_response.dart
  lib/src/service/platform_service.dart
Labels: enhancement, P0

#1281 Feature/1263 - Added Session Store
  .trunk/.gitignore
  .trunk/trunk.yaml
  android/build.gradle
  android/src/main/kotlin/live/hms/hmssdk_flutter/HMSErrorLogger.kt
  android/src/main/kotlin/live/hms/hmssdk_flutter/HmssdkFlutterPlugin.kt
  android/src/main/kotlin/live/hms/hmssdk_flutter/methods/HMSSessionMetadataAction.kt
  android/src/main/kotlin/live/hms/hmssdk_flutter/methods/HMSSessionStoreAction.kt
  example/android/app/build.gradle
  example/ios/Podfile.lock
  example/ios/Runner/Info.plist
  example/lib/common/bottom_sheets/app_settings_bottom_sheet.dart
  example/lib/common/widgets/audio_tile.dart
  example/lib/meeting/meeting_store.dart
  ios/Classes/Actions/HMSAudioAction.swift
  ios/Classes/Actions/HMSAudioDeviceAction.swift
  ios/Classes/Actions/HMSCameraControlsAction.swift
  ios/Classes/Actions/HMSCommonAction.swift
  ios/Classes/Actions/HMSHLSAction.swift
  ios/Classes/Actions/HMSMessageAction.swift
  ios/Classes/Actions/HMSPIPAction.swift
  ios/Classes/Actions/HMSRecordingAction.swift
  ios/Classes/Actions/HMSRemoteVideoTrackAction.swift
  ios/Classes/Actions/HMSRoomAction.swift
  ios/Classes/Actions/HMSSessionStoreAction.swift
  ios/Classes/Actions/HMSVideoAction.swift
  ios/Classes/Models/HMSAudioFilePlayerNodeExtension.swift
  ios/Classes/Models/HMSErrorLogger.swift
  ios/Classes/Models/HMSSessionStoreKeyChangeListener.swift
  ios/Classes/SwiftHmssdkFlutterPlugin.swift
  ios/Classes/Views/HMSPiPView.swift
  lib/assets/sdk-versions.json
  sample apps/flutter-hls-quickstart/lib/main.dart
Labels: enhancement, P0

#1312 Fixed spotlight mode
  example/lib/common/peer_widgets/more_option.dart
  example/lib/meeting/meeting_store.dart
Labels: P0, app-UX

#1317 Added fix for removeKeyChangeListener method
  android/src/main/kotlin/live/hms/hmssdk_flutter/HmssdkFlutterPlugin.kt
  ios/Classes/SwiftHmssdkFlutterPlugin.swift
  lib/src/model/hms_session_store.dart
  lib/src/service/platform_service.dart
Labels: bug, P0

#1320 Fixed comments
  android/src/main/kotlin/live/hms/hmssdk_flutter/HmssdkFlutterPlugin.kt
  ios/Classes/Actions/HMSSessionStoreAction.swift
  ios/Classes/SwiftHmssdkFlutterPlugin.swift
  lib/src/model/hms_session_store.dart
Labels: bug, P0

#1321 Spotlight app fix
  example/lib/meeting/meeting_store.dart
Labels: P0, app-UX

#1322 Update README.md
  README.md
Labels: documentation

#1325 Updated android SDK
  example/ExampleAppChangelog.txt
  lib/assets/sdk-versions.json
  lib/src/model/hms_video_track_setting.dart
Labels: chore

#1326 Crash fix if file is not created
  example/lib/common/bottom_sheets/app_settings_bottom_sheet.dart
  example/lib/common/util/log_writer.dart
Labels: P0, app-UX

#1327 Fix lint warnings
  android/src/main/kotlin/live/hms/hmssdk_flutter/HMSAudioTrackSettingsExtension.kt
  android/src/main/kotlin/live/hms/hmssdk_flutter/HMSChangeTrackStateRequestExtension.kt
  android/src/main/kotlin/live/hms/hmssdk_flutter/HMSHLSVariantExtension.kt
  android/src/main/kotlin/live/hms/hmssdk_flutter/HMSLogSettings.kt
  android/src/main/kotlin/live/hms/hmssdk_flutter/HMSLogsExtension.kt
  android/src/main/kotlin/live/hms/hmssdk_flutter/HMSMessageExtension.kt
  android/src/main/kotlin/live/hms/hmssdk_flutter/HMSMessageRecipientExtension.kt
  android/src/main/kotlin/live/hms/hmssdk_flutter/HMSNetworkQualityExtension.kt
  android/src/main/kotlin/live/hms/hmssdk_flutter/HMSPeerUpdateExtension.kt
  android/src/main/kotlin/live/hms/hmssdk_flutter/HMSPreviewExtension.kt
  android/src/main/kotlin/live/hms/hmssdk_flutter/HMSRemovedFromRoomExtension.kt
  android/src/main/kotlin/live/hms/hmssdk_flutter/HMSRoleChangedExtension.kt
  android/src/main/kotlin/live/hms/hmssdk_flutter/HMSRoleExtension.kt
  android/src/main/kotlin/live/hms/hmssdk_flutter/HMSRoomUpdateExtension.kt
  android/src/main/kotlin/live/hms/hmssdk_flutter/HMSRtmpStreamingState.kt
  android/src/main/kotlin/live/hms/hmssdk_flutter/HMSSessionMetadataExtension.kt
  android/src/main/kotlin/live/hms/hmssdk_flutter/HMSSpeakerExtension.kt
  android/src/main/kotlin/live/hms/hmssdk_flutter/HMSTrackInitStateExtension.kt
  android/src/main/kotlin/live/hms/hmssdk_flutter/HMSTrackSettingsExtension.kt
  android/src/main/kotlin/live/hms/hmssdk_flutter/HMSTrackUpdateExtension.kt
  android/src/main/kotlin/live/hms/hmssdk_flutter/HMSVideoResolutionExtension.kt
  android/src/main/kotlin/live/hms/hmssdk_flutter/HMSVideoTrackSettingsExtension.kt
  android/src/main/kotlin/live/hms/hmssdk_flutter/HmssdkFlutterPlugin.kt
  android/src/main/kotlin/live/hms/hmssdk_flutter/hms_role_components/AudioParamsExtension.kt
  android/src/main/kotlin/live/hms/hmssdk_flutter/hms_role_components/PermissionParamsExtension.kt
  android/src/main/kotlin/live/hms/hmssdk_flutter/hms_role_components/VideoParamsExtension.kt
  android/src/main/kotlin/live/hms/hmssdk_flutter/methods/HMSAudioDeviceAction.kt
  android/src/main/kotlin/live/hms/hmssdk_flutter/methods/HMSHLSAction.kt
  android/src/main/kotlin/live/hms/hmssdk_flutter/methods/HMSMessageAction.kt
  android/src/main/kotlin/live/hms/hmssdk_flutter/methods/HMSRecordingAction.kt
  android/src/main/kotlin/live/hms/hmssdk_flutter/methods/HMSRoomAction.kt
  android/src/main/kotlin/live/hms/hmssdk_flutter/views/HMSVideoView.kt
  android/src/main/kotlin/live/hms/hmssdk_flutter/views/HMSVideoViewFactory.kt
  example/android/app/src/main/kotlin/live/hms/flutter/MainActivity.kt
  ios/Classes/Actions/HMSSessionStoreAction.swift
  ios/Classes/SwiftHmssdkFlutterPlugin.swift
  sample apps/bloc/android/app/src/main/kotlin/com/example/demo_app_with_100ms_and_bloc/MainActivity.kt
  sample apps/flutter-audio-room-quickstart/android/app/src/main/kotlin/com/example/flutter_audio_room_quickstart/MainActivity.kt
  sample apps/flutter-hls-quickstart/android/app/src/main/kotlin/com/example/flutter_hls_quickstart/MainActivity.kt
  sample apps/flutter-quickstart-app/android/app/src/main/kotlin/com/example/flutter_integration_guide/MainActivity.kt
  sample apps/getx/android/app/src/main/kotlin/com/example/demo_with_getx_and_100ms/MainActivity.kt
  sample apps/mobx/android/app/src/main/kotlin/com/example/zoom/MainActivity.kt
  sample apps/riverpod/android/app/src/main/kotlin/com/example/example_riverpod/MainActivity.kt
Labels: chore

#1328 corrected dart analyze warnings
  example/lib/common/app_dialogs/audio_device_change_dialog.dart
  example/lib/common/app_dialogs/audio_mode_select_dialog.dart
  example/lib/common/app_dialogs/change_simulcast_layer_option_dialog.dart
  example/lib/common/app_dialogs/hls_aspect_ratio_option_dialog.dart
  example/lib/common/app_dialogs/stats_for_nerds.dart
  example/lib/common/util/utility_components.dart
  example/lib/common/util/utility_function.dart
  example/lib/common/widgets/share_link_option.dart
  example/lib/hms_sdk_interactor.dart
  example/lib/meeting_modes/hero_mode.dart
Labels: chore

#1332 Updated dart constraints
  example/pubspec.yaml
  pubspec.yaml
Labels: chore

#1336 Chore/correct lint warnings
  .trunk/trunk.yaml
  README.md
  example/android/Gemfile.lock
  example/ios/Gemfile.lock
  example/ios/Podfile.lock
  example/pubspec.lock
  pubspec.lock
  sample apps/bloc/lib/home_page.dart
Labels: chore

#1341 updated iOS SDK version
  example/ExampleAppChangelog.txt
  example/android/Gemfile.lock
  example/ios/Gemfile.lock
  example/ios/Podfile.lock
  example/pubspec.lock
  lib/assets/sdk-versions.json
Labels: chore

#1343 Updated Package version
  .trunk/trunk.yaml
  example/ExampleAppChangelog.txt
  example/ios/Podfile.lock
  example/lib/common/widgets/video_view.dart
  example/pubspec.lock
  example/pubspec.yaml
  lib/assets/sdk-versions.json
  lib/src/ui/meeting/hms_video_view.dart
  pubspec.yaml
Labels: chore
