Repository 100mslive/100ms-flutter, pull requests merged in 2023-01, with the labels that each got.

#1042 Corrected SDK versions file path
  android/build.gradle
  ios/hmssdk_flutter.podspec
Labels: bug, P0

#1052 updated ReadMe
  README.md
Labels: documentation

#1057 foreground service
  example/android/app/src/main/AndroidManifest.xml
  example/lib/hls-streaming/hls_broadcaster_page.dart
  example/pubspec.lock
  example/pubspec.yaml
Labels: enhancement, P1

#1061 Updated android sdk
  android/src/main/kotlin/live/hms/hmssdk_flutter/HMSPeerExtension.kt
  android/src/main/kotlin/live/hms/hmssdk_flutter/HMSRtcStatsExtension.kt
  android/src/main/kotlin/live/hms/hmssdk_flutter/HMSSimulcastLayerExtension.kt
  android/src/main/kotlin/live/hms/hmssdk_flutter/HmssdkFlutterPlugin.kt
  android/src/main/kotlin/live/hms/hmssdk_flutter/views/HMSVideoView.kt
  android/src/main/kotlin/live/hms/hmssdk_flutter/views/HMSVideoViewFactory.kt
  example/ExampleAppChangelog.txt
  example/android/Gemfile.lock
  example/android/app/src/main/AndroidManifest.xml
  example/ios/Gemfile.lock
  example/ios/Podfile.lock
  example/lib/common/bottom_sheets/notification_settings.dart
  example/lib/common/ui/organisms/rtc_stats_view.dart
  example/lib/common/ui/organisms/video_view.dart
  example/lib/data_store/meeting_store.dart
  example/lib/model/peer_track_node.dart
  example/lib/model/rtc_stats.dart
  example/pubspec.lock
  ios/Classes/Models/HMSSimulcastLayerDefinitionExtension.swift
  ios/Classes/Models/HMSStatsExtension.swift
  ios/Classes/SwiftHmssdkFlutterPlugin.swift
  ios/Classes/Views/HMSFlutterPlatformViewFactory.swift
  lib/assets/sdk-versions.json
  lib/src/enum/hms_simulcast_layer.dart
  lib/src/model/hms_local_video_stats.dart
  lib/src/model/hms_quality_limitation_reasons.dart
  lib/src/model/hms_stats_listener.dart
  lib/src/service/platform_service.dart
  lib/src/ui/meeting/hms_video_view.dart
Labels: enhancement, P0

#1069 added logs when track is nil
  ios/Classes/SwiftHmssdkFlutterPlugin.swift
  ios/Classes/Views/HMSFlutterPlatformView.swift
  ios/Classes/Views/HMSFlutterPlatformViewFactory.swift
Labels: bug, P1

#1066 Added error logs if track is null
  android/src/main/kotlin/live/hms/hmssdk_flutter/HMSRtcStatsExtension.kt
  android/src/main/kotlin/live/hms/hmssdk_flutter/HmssdkFlutterPlugin.kt
  android/src/main/kotlin/live/hms/hmssdk_flutter/views/HMSVideoView.kt
  android/src/main/kotlin/live/hms/hmssdk_flutter/views/HMSVideoViewFactory.kt
  ios/Classes/SwiftHmssdkFlutterPlugin.swift
  ios/Classes/Views/HMSFlutterPlatformView.swift
  ios/Classes/Views/HMSFlutterPlatformViewFactory.swift
Labels: bug, P1

#1081 1059/updated switch av methods
  android/src/main/kotlin/live/hms/hmssdk_flutter/HmssdkFlutterPlugin.kt
  android/src/main/kotlin/live/hms/hmssdk_flutter/methods/HMSAudioAction.kt
  android/src/main/kotlin/live/hms/hmssdk_flutter/methods/HMSVideoAction.kt
  example/lib/common/ui/organisms/one_to_one_mode.dart
  example/lib/data_store/meeting_store.dart
  example/lib/hls-streaming/hls_broadcaster_page.dart
  example/lib/hls-streaming/hls_screen_controller.dart
  example/lib/hms_sdk_interactor.dart
  example/lib/preview/preview_details.dart
  example/lib/preview/preview_page.dart
  example/lib/preview/preview_store.dart
  ios/Classes/Models/HMSAudioAction.swift
  ios/Classes/Models/HMSVideoAction.swift
  ios/Classes/SwiftHmssdkFlutterPlugin.swift
  lib/src/common/platform_methods.dart
  lib/src/hmssdk.dart
Labels: enhancement, P1

#1082 HmsIOSScreenshare config
  android/src/main/kotlin/live/hms/hmssdk_flutter/HmssdkFlutterPlugin.kt
  example/ios/Podfile.lock
  example/lib/hms_sdk_interactor.dart
  example/lib/preview/preview_details.dart
  ios/Classes/Models/HMSTrackSettingsExtension.swift
  ios/Classes/SwiftHmssdkFlutterPlugin.swift
  lib/hmssdk_flutter.dart
  lib/src/hmssdk.dart
  lib/src/manager/hms_sdk_manager.dart
  lib/src/model/hms_ios_screenshare_config.dart
Labels: enhancement, P0

#1092 more option icon added
  example/lib/common/peer_widgets/more_option.dart
  example/lib/common/widgets/peer_tile.dart
Labels: enhancement, P1, sample-app

#1104 updated Native SDK versions
  example/android/Gemfile.lock
  example/ios/Gemfile.lock
  example/ios/Podfile.lock
  example/pubspec.lock
  lib/assets/sdk-versions.json
Labels: enhancement, P0

#1079 Pip implementation
  example/ExampleAppChangelog.txt
  example/android/Gemfile.lock
  example/android/app/build.gradle
  example/ios/Gemfile.lock
  example/ios/Podfile.lock
  example/ios/Runner.xcodeproj/project.pbxproj
  example/ios/Runner/Info.plist
  example/ios/Runner/Runner.entitlements
  example/lib/common/bottom_sheets/more_settings_bottom_sheet.dart
  example/lib/common/util/utility_function.dart
  example/lib/hms_sdk_interactor.dart
  example/lib/main.dart
  example/lib/meeting/meeting_store.dart
  ios/Classes/Models/HMSPIPAction.swift
  ios/Classes/PiPView.swift
  ios/Classes/SwiftHmssdkFlutterPlugin.swift
  lib/hmssdk_flutter.dart
  lib/src/common/platform_methods.dart
  lib/src/hmssdk.dart
  lib/src/model/hms_android_pip_controller.dart
  lib/src/model/hms_ios_pip_controller.dart
  sample apps/bloc/pubspec.lock
  sample apps/flutter-quickstart-app/pubspec.lock
  sample apps/getx/pubspec.lock
  sample apps/mobx/pubspec.lock
  sample apps/riverpod/pubspec.lock
Labels: enhancement, P0
