Repository 100mslive/100ms-flutter, pull requests merged in 2024-07, with the labels that each got.

#1798 Fixed noise cancellation property on android from dashboard
  packages/hms_room_kit/lib/src/meeting/meeting_store.dart
  packages/hmssdk_flutter/example/ExampleAppChangelog.txt
  packages/hmssdk_flutter/example/android/app/build.gradle
  packages/hmssdk_flutter/example/ios/Gemfile.lock
  packages/hmssdk_flutter/example/ios/Runner/Info.plist
  packages/hmssdk_flutter/ios/Classes/Actions/HMSNoiseCancellationControllerAction.swift
  packages/hmssdk_flutter/lib/assets/sdk-versions.json
Labels: release

#1802 Updated SDK version and added change log
  packages/hms_room_kit/CHANGELOG.md
  packages/hms_room_kit/example/pubspec.lock
  packages/hms_room_kit/pubspec.lock
  packages/hms_room_kit/pubspec.yaml
  packages/hmssdk_flutter/CHANGELOG.md
  packages/hmssdk_flutter/example/ExampleAppChangelog.txt
  packages/hmssdk_flutter/example/pubspec.lock
Labels: release

#1805 Fix: Leave room renders blank screen
  packages/hms_room_kit/lib/src/meeting/meeting_page.dart
  packages/hms_room_kit/lib/src/meeting/meeting_store.dart
  packages/hms_room_kit/lib/src/widgets/bottom_sheets/end_service_bottom_sheet.dart
  packages/hmssdk_flutter/example/android/app/build.gradle
  packages/hmssdk_flutter/example/ios/Runner/Info.plist
Labels: release

#1799 Release 1.10.5: Develop to main
  README.md
  docs/static/img/appstore.svg
  docs/static/img/googleplay.svg
  packages/hms_room_kit/CHANGELOG.md
  packages/hms_room_kit/README.md
  packages/hms_room_kit/example/pubspec.lock
  packages/hms_room_kit/example/pubspec.yaml
  packages/hms_room_kit/lib/src/layout_api/hms_conferencing_items.dart
  packages/hms_room_kit/lib/src/layout_api/hms_room_layout.dart
  packages/hms_room_kit/lib/src/meeting/meeting_page.dart
  packages/hms_room_kit/lib/src/meeting/meeting_store.dart
  packages/hms_room_kit/lib/src/model/transcript_store.dart
  packages/hms_room_kit/lib/src/preview/preview_store.dart
  packages/hms_room_kit/lib/src/widgets/bottom_sheets/chat_only_bottom_sheet.dart
  packages/hms_room_kit/lib/src/widgets/bottom_sheets/end_service_bottom_sheet.dart
  packages/hms_room_kit/lib/src/widgets/common_widgets/transcription_view.dart
  packages/hms_room_kit/lib/src/widgets/tab_widgets/chat_participants_tab_bar.dart
  packages/hms_room_kit/pubspec.lock
  packages/hms_room_kit/pubspec.yaml
  packages/hmssdk_flutter/CHANGELOG.md
  packages/hmssdk_flutter/README.md
  packages/hmssdk_flutter/android/src/main/kotlin/live/hms/hmssdk_flutter/methods/HMSNoiseCancellationControllerAction.kt
  packages/hmssdk_flutter/example/ExampleAppChangelog.txt
  packages/hmssdk_flutter/example/android/app/build.gradle
  packages/hmssdk_flutter/example/ios/Gemfile.lock
  packages/hmssdk_flutter/example/ios/Podfile.lock
  packages/hmssdk_flutter/example/ios/Runner/Info.plist
  packages/hmssdk_flutter/example/lib/foreground_task_handler.dart
  packages/hmssdk_flutter/example/pubspec.lock
  packages/hmssdk_flutter/example/pubspec.yaml
  packages/hmssdk_flutter/ios/Classes/Actions/HMSNoiseCancellationControllerAction.swift
  packages/hmssdk_flutter/ios/Classes/SwiftHmssdkFlutterPlugin.swift
  packages/hmssdk_flutter/lib/assets/sdk-versions.json
  packages/hmssdk_flutter/pubspec.yaml
Labels: release

#1806 Chore: Updated sdk versions
  packages/hms_room_kit/example/pubspec.yaml
  packages/hms_room_kit/pubspec.yaml
  packages/hmssdk_flutter/example/pubspec.lock
  packages/hmssdk_flutter/example/pubspec.yaml
  packages/hmssdk_flutter/lib/assets/sdk-versions.json
  packages/hmssdk_flutter/pubspec.yaml
Labels: release

#1796 ISS-22778: Updated DateTime parsing
  packages/hms_room_kit/lib/src/widgets/bottom_sheets/chat_bottom_sheet.dart
  packages/hms_room_kit/lib/src/widgets/common_widgets/message_container.dart
  packages/hmssdk_flutter/android/src/main/kotlin/live/hms/hmssdk_flutter/HMSMessageExtension.kt
  packages/hmssdk_flutter/android/src/main/kotlin/live/hms/hmssdk_flutter/hls_player/HMSHLSCueExtension.kt
  packages/hmssdk_flutter/ios/Classes/HLSPlayer/HMSHLSCueExtension.swift
  packages/hmssdk_flutter/ios/Classes/Models/HMSMessageExtension.swift
  packages/hmssdk_flutter/lib/src/model/hls_player/hms_hls_cue.dart
  packages/hmssdk_flutter/lib/src/model/hms_date_extension.dart
  packages/hmssdk_flutter/lib/src/model/hms_message.dart
Labels: chore, release

#1801 ISS-22877: Added `switch Role` option in prebuilt if the peer has permission to change the role
  packages/hms_room_kit/lib/src/assets/icons/peer_settings.svg
  packages/hms_room_kit/lib/src/widgets/app_dialogs/change_role_option_dialog.dart
  packages/hms_room_kit/lib/src/widgets/bottom_sheets/change_role_bottom_sheet.dart
  packages/hms_room_kit/lib/src/widgets/bottom_sheets/participants_bottom_sheet.dart
  packages/hms_room_kit/lib/src/widgets/bottom_sheets/remote_peer_bottom_sheet.dart
  packages/hms_room_kit/lib/src/widgets/common_widgets/hms_dropdown.dart
Labels: enhancement, release
